version: '3.8'

services:
    vue:
        container_name: tax_stopper
        build: ./docker/
        ports:
            - 80:80
            - 8080:8080
        privileged: true
        volumes:
            - ./src:/app
            - ./docs:/usr/local/apache2/htdocs/
        environment:
            TZ: 'Asia/Tokyo'
        tty: true
        stdin_open: true
    db:
        container_name: tax_stopper_db
        build: ./docker/mysql
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        env_file:
            - ./docker/env

    py:
        container_name: tax_stopper_backend
        build: ./docker/py
        ports:
            - 8000:50201
        volumes:
            - ./src/backend:/py/
        env_file:
            - ./docker/env
        tty: true
        stdin_open: true
        privileged: true
        command: bash -c "uvicorn main:app --host 0.0.0.0 --port 50201 --reload"

    # phpMyAdmin dev
    # phpmyadmin:
    #     container_name: dev_phpmyadmin
    #     image: phpmyadmin/phpmyadmin
    #     environment:
    #         - PMA_ARBITRARY=1
    #         - PMA_HOSTS=tax_stopper_db
    #         - PMA_USER=root
    #         - PMA_PASSWORD=root
    #     ports:
    #         - 3000:80