version: '3.8'

services:
    vue:
        container_name: tax_stopper
        build: ./docker/
        ports:
            - 80:80
            - 8080:8080
        privileged: true
        volumes:
            - ./src:/app
            - ./docs:/usr/local/apache2/htdocs/
        environment:
            TZ: 'Asia/Tokyo'
        tty: true
        stdin_open: true
    db:
        container_name: tax_stopper_db
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        env_file:
            - ./docker/mysql/env

    py:
        container_name: tax_stopper_backend
        build: ./docker/py
        ports:
            - 8000:8000
        volumes:
            - ./src/backend:/py/src
        env_file:
            - ./docker/mysql/env
        tty: true
        stdin_open: true
        privileged: true

    # phpMyAdmin dev
    phpmyadmin:
        container_name: dev_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=tax_stopper_db
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 3000:80