version: '3.8'

services:
    vue:
        container_name: tax_stopper
        build: ./docker/
        ports:
            - 80:80
            - 8080:8080
        privileged: true
        volumes:
            - ./src:/app
            - ./docs:/usr/local/apache2/htdocs/
        environment:
            TZ: 'Asia/Tokyo'
        tty: true
        stdin_open: true
    db:
        container_name: tax_stopper_db
        image: mysql:5.7
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        env_file:
            - ./docker/mysql/env
        ports:
            - 3306:3306