FROM python:3.10.6-bullseye
WORKDIR /py

COPY requirements.txt .
RUN apt update && apt install -y vim
RUN apt install -y python-dev python3-dev default-libmysqlclient-dev
RUN pip install --upgrade pip
RUN pip install -r requirements.txt