FROM httpd:2.4
WORKDIR /app

RUN apt-get update \
&& apt-get -y install --no-install-recommends \
nodejs \
npm \
curl \
&& apt-get clean

RUN npm install -g n && n stable \
&& apt purge -y \
    nodejs \
    npm

RUN ["/bin/bash", "-c", " \
    source ~/.bashrc \
    && npm install vue \
    && npm install -g @vue/cli \
"]

EXPOSE 80